// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShopApi.Models;

namespace ShopApi.Migrations
{
    [DbContext(typeof(FamilyShopContext))]
    [Migration("20190729191856_mon_3_18pm")]
    partial class mon_3_18pm
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ShopApi.Models.Private.Family", b =>
                {
                    b.Property<long>("familyID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.HasKey("familyID");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("ShopApi.Models.Private.List", b =>
                {
                    b.Property<long>("listID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("description");

                    b.Property<long?>("familyID");

                    b.Property<string>("name");

                    b.HasKey("listID");

                    b.HasIndex("familyID");

                    b.ToTable("Lists");
                });

            modelBuilder.Entity("ShopApi.Models.Private.ListItem", b =>
                {
                    b.Property<long>("itemID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("description");

                    b.Property<long?>("listID");

                    b.Property<string>("title");

                    b.Property<long>("userID");

                    b.HasKey("itemID");

                    b.HasIndex("listID");

                    b.HasIndex("userID");

                    b.ToTable("ListItems");
                });

            modelBuilder.Entity("ShopApi.Models.Private.User", b =>
                {
                    b.Property<long>("userID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("email");

                    b.Property<long>("familyID");

                    b.Property<string>("passwordHash");

                    b.Property<byte[]>("passwordSalt");

                    b.Property<string>("username");

                    b.HasKey("userID");

                    b.HasIndex("familyID")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShopApi.Models.Private.List", b =>
                {
                    b.HasOne("ShopApi.Models.Private.Family", "family")
                        .WithMany("lists")
                        .HasForeignKey("familyID");
                });

            modelBuilder.Entity("ShopApi.Models.Private.ListItem", b =>
                {
                    b.HasOne("ShopApi.Models.Private.List", "list")
                        .WithMany()
                        .HasForeignKey("listID");

                    b.HasOne("ShopApi.Models.Private.User", "user")
                        .WithMany()
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShopApi.Models.Private.User", b =>
                {
                    b.HasOne("ShopApi.Models.Private.Family", "family")
                        .WithOne("admin")
                        .HasForeignKey("ShopApi.Models.Private.User", "familyID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
